Repository opencloud-eu/desktop, pull requests merged in 2025-07, with the labels that each got.

#355 OAuth: Only display user name in an error if we have one
  src/libsync/creds/idtoken.cpp
  src/libsync/creds/idtoken.h
  src/libsync/creds/oauth.cpp
Labels: Type:Bug

#411 Use LocalInfo in fileChanged
  src/gui/folder.cpp
  src/libsync/discoveryinfo.cpp
  src/libsync/discoveryinfo.h
  src/libsync/filesystem.cpp
  src/libsync/filesystem.h
  src/libsync/propagatedownload.cpp
  src/libsync/propagateuploadtus.cpp
  src/libsync/propagateuploadv1.cpp
Labels: Type:Maintenance

#413 Test: remove redundant host parameter
  test/gui/shared/steps/account_context.py
  test/gui/tst_addAccount/test.feature
  test/gui/tst_removeAccountConnection/test.feature
  test/gui/tst_syncing/test.feature
Labels: Type:Test
