Repository opencloud-eu/desktop, pull requests merged in 2025-06, with the labels that each got.

#310 Retry oauth refresh if wellknown request failed
  src/libsync/creds/oauth.cpp
  src/libsync/creds/oauth.h
Labels: Type:Bug

#311 Fix reuse of existing Space folders
  src/gui/folderman.cpp
  src/gui/folderwizard/folderwizard.cpp
  src/gui/folderwizard/folderwizardlocalpath.cpp
Labels: Type:Bug

#308 Since Qt 6.8 network headers are normalized to lowercase
  CMakeLists.txt
  src/libsync/httplogger.cpp
Labels: Type:Breaking-Change

#282 Test(refactor): fix sync path in windows
  test/gui/config.sample.ini
  test/gui/shared/scripts/bdd_hooks.py
  test/gui/shared/scripts/helpers/ConfigHelper.py
  test/gui/shared/scripts/helpers/SetupClientHelper.py
  test/gui/shared/scripts/helpers/SyncHelper.py
  test/gui/shared/scripts/helpers/WebUIHelper.py
  test/gui/shared/scripts/pageObjects/Toolbar.py
  test/gui/shared/steps/sync_context.py
  test/gui/tst_activity/test.feature
Labels: Type:Test

#328 Test(refactor): Clean user in windows
  test/gui/shared/scripts/bdd_hooks.py
Labels: Type:Test
